### ISSUE TITLE
It will logout when the browser reloads

### ISSUE THREAD

**Issue by neverknoww** [giekaton/php-metamask-user-login#10]
Hello,

Thank you for your contribution. It works perfectly but anyone able to figure a way to make it stay connect even when the browser refreshed? Should I do it in the javascript file like https://stackoverflow.com/questions/68345619/how-to-keep-metamask-connection-to-the-ui-persistent-with-web3-react

or

I should add a new field in the database so it will keep a record of the user logged in or logged out status?

Thanks in advance

**Comment by giekaton** [comment]
You need to store auth token somewhere, but not sure what would be a secure way to do this.
