### ISSUE TITLE
No session

### ISSUE THREAD

**Issue by asilvafx** [giekaton/php-metamask-user-login#12]
really cool script although it doesnt seem to create a session. Soon as you refresh the page it kills the current login

**Comment by giekaton** [comment]
It's based on JWT, not on sessions.

**Comment by asilvafx** [comment]
> It's based on JWT, not on sessions.

And how you keep the users loggedIn? 🤔

**Comment by giekaton** [comment]
You need to store auth token somewhere, but I'm not sure what would be a secure way to do this.

**Comment by asilvafx** [comment]
Exactly, What about store the address using php session. Im trying to implement that change on server.php
