### ISSUE TITLE
How remove deprecation of these script

### ISSUE THREAD

**Issue by nitingupta-123** [giekaton/php-metamask-user-login#15]
<script src="https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js"></script>

<script type="text/javascript" src="https://unpkg.com/web3modal@1.9.0/dist/index.js"></script>

**Comment by giekaton** [comment]
![Screenshot 2022-03-16 191131](https://user-images.githubusercontent.com/14371026/158648213-4e082cc6-ae04-4f78-ac21-2467c1f57422.png)

**Comment by nitingupta-123** [comment]
could you please tell me the way to remove above deprecation...?

**Comment by giekaton** [comment]
The web3 API has changed, and so the code needs to be updated, similarly as described in the screenshot. I don't have time to work on this right now, but pull requests are welcome.

**Comment by ValentinJapan** [comment]
To solve this you can use the new version of web3modal@1.9.7 (https://unpkg.com/web3modal@1.9.7/dist/index.js)

**Comment by giekaton** [comment]
> To solve this you can use the new version of web3modal@1.9.7 (https://unpkg.com/web3modal@1.9.7/dist/index.js)

This is not sufficient. I will provide a fix soon.
