### ISSUE TITLE
How to output ETH Balance

### ISSUE THREAD

**Issue by StohnIO** [giekaton/php-metamask-user-login#17]
This is a nice clever script. Is there an easy way to output your ETH balance or other token you have in Meta Mask?

**Comment by bl4km0uz** [comment]
Up

**Comment by giekaton** [comment]
It uses web3.js to connect to the blockchain. How to query an address balance, see this: https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#getbalance
