### ISSUE TITLE
Is it work in 2020?

### ISSUE THREAD

**Issue by pticun** [giekaton/php-metamask-user-login#2]
Is it work in 2020?

**Comment by giekaton** [comment]
No, it seems that the initial connection with MetaMask needs to be updated, as it has changed on the MetaMask side.

It's a relatively simple update, as it has been updated in this repo: https://github.com/giekaton/Set-in-Block

Other parts of this user authentication code should work as expected.

**Comment by giekaton** [comment]
After the latest update, it works in 2021.
