### ISSUE TITLE
The Login has stopped working with the error "Attempt to read property "request" on null"

### ISSUE THREAD

**Issue by amirrazor** [giekaton/php-metamask-user-login#20]
Hello, i am making use of your metamask login for my master thesis project and since yesterday i am getting the error: 

"Attempt to read property "request" on null in <b>C:\xampp\htdocs\my-project\backend\server.php</b> on line <b>14</b><br />"

when trying to log in with any account using metamask. I tried to login in your demo page and got the same error. Do you know where this problem is coming from? i tried reinstalling metamask extension and trying it on different browser but i get the same error. Could the problem be from my side? Can you please test it and find the problem?

**Comment by amirrazor** [comment]
The login works now on your demo page. That is great. Can you please upload the fix on github? Thank you in advance.

**Comment by Cryptdk** [comment]
I still see the issue on the Demo page:

<br />
<b>Warning</b>:  Attempt to read property "request" on null in <b>/home/setinblo/domains/setinblock.com/public/php-metamask-user-login/backend/server.php</b> on line <b>14</b><br />

**Comment by giekaton** [comment]
I found the issue and updated the demo site for a test. Now reverted back, and looking for a proper fix.

**Comment by giekaton** [comment]
Updated the repository. It should work now!

**Comment by amirrazor** [comment]
The problem is solved. Thanks in advance.
