### ISSUE TITLE
WebSocket connection to 'ws://localhost:8545/' failed

### ISSUE THREAD

**Issue by old-phoenix** [giekaton/php-metamask-user-login#26]
index.js:94 WebSocket connection to 'ws://localhost:8545/' failed

It isnt possible to sign the message because there is only this error

**Comment by giekaton** [comment]
This might be related to the new Walletconnect 2.0 update, released just a few days ago. More info here: https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/dapps

I don't have time to work on this currently. However, if anyone else is interested in contributing, they are always welcome to submit pull requests.

**Comment by pablohastings** [comment]
I think it might be from an updated version of web3.js.  This person's blog is based on this example:
https://blog.gaiterjones.com/php-passwordless-user-login-with-web3-connect-and-metamask/

and it still works.  The difference seems to be a link to a specific version of web3:
<script src="//unpkg.com/web3@1.6.1/dist/web3.min.js"></script>

where your demo is using the latest web3 but versioned other files:

<script src="https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js"></script>
--
  | <script type="text/javascript" src="https://unpkg.com/web3modal@1.9.8/dist/index.js"></script>
  | <script type="text/javascript" src="https://unpkg.com/@walletconnect/web3-provider@1.7.8/dist/umd/index.min.js"></script>

**Comment by giekaton** [comment]
Thank you for the info. This indeed solved the issue. I have now pushed the fix to the repository.
