### ISSUE TITLE
Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/html/server/lib/Keccak/Keccak.php on line 11

### ISSUE THREAD

**Issue by spuqe** [giekaton/php-metamask-user-login#7]
`Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/html/Earn/server/lib/Keccak/Keccak.php on line 11`
There seems to be an problem yes. 

Lines 11-17:
```
final class Keccak
{
    private const KECCAK_ROUNDS = 24;
    private const LFSR = 0x01;
    private const ENCODING = '8bit';
    private static $keccakf_rotc = [1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 2, 14, 27, 41, 56, 8, 25, 43, 62, 18, 39, 61, 20, 44];
    private static $keccakf_piln = [10, 7, 11, 17, 18, 3, 5, 16, 8, 21, 24, 4, 15, 23, 19, 13, 12,2, 20, 14, 22, 9, 6, 1];
    private static $x64 = (PHP_INT_SIZE === 8);

```

**Comment by Jishai** [comment]
+1 running into the same issue as @spuqe

**Comment by giekaton** [comment]
When/where is this error occuring? How to reproduce it?

**Comment by Jishai** [comment]
Getting this error right after clicking on "Log in" and selecting Metamask.

`[Sat Oct 23 19:04:11.659328 2021] [:error] [pid 13308] [client 162.158.88.68:55014] PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/html/connect2/server/lib/Keccak/Keccak.php on line 11, referer: https://d.art/connect2/`

**Comment by giekaton** [comment]
Which PHP version do you use?

**Comment by Jishai** [comment]
7.0

**Comment by giekaton** [comment]
It looks like Keccak library requires PHP version at least 7.1. Try switching to a newer PHP, and it should work then.

**Comment by Jishai** [comment]
@giekaton upgrading to 7.4 fixed it! Thanks for your quick reply.
